apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-kubernetes-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/crossplane-argocd-lab.git
    targetRevision: main
    path: crossplane/provider-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - ServerSideApply=true